In [7]:
import torch
print(torch.__version__)

import numpy as np

2.5.1+cu124


# 1.Tensor的理解：
    1.常数，scaler:0阶张量
    2.向量,vector,1阶张量
    3.矩阵,matrix:2阶张量
    4.3阶张量
# 2. 创建张量的方法：
     1.使用列表创建Tensor
     2.使用numpy数组创建Tensor
     3.通过torch的API创建Tensor
     
# 3. 张量的方法和属性
    1.tensor.item(),当tensor中只有一个元素可以用的时候
    2.Tensor转为ndarray
    3.形状修改，tensor.view((3, 4)), 类似numpy中的reshape,是一种浅拷贝
    4.获取维数、转置、轴滚动。
    5.在方法后加_，会原地修改，相当于Tensorflow里的inplace

# 2. 创建张量的方法：

In [8]:
# 1.使用列表创建Tensor
t1 = torch.Tensor([1, 2, 3])
print(t1)
"""
tensor([1., 2., 3.])
"""

# 2.使用numpy数组创建Tensor
array1 = np.arange(12).reshape(3, 4)

t2 = torch.Tensor(array1)
print(t2)

tensor([1., 2., 3.])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [9]:
t2[0:1,:] #切片

tensor([[0., 1., 2., 3.]])

In [10]:
# 3.通过torch的API创建Tensor
"""
torch.empty(3,4)：创建3行四列的空的tensor,会用无用的数据进行填充
torch.ones([3,4]):三行四列全为1的tensor
torch.zeros([3,4]):三行四列全为0的tensor
torch.rand([3,4]):三行四列随机值在[0,1]之间的值
torch.randint(low = 0, high = 10, size = [3, 4]) 创建3*4的随机整数的Tensor，值区间：[low, high]
torch.randn([3,4]) 均值为0，方差为1,3*4的tensor
"""
print(torch.empty(3,4))
print(torch.ones([3,4]))
print(torch.zeros([3,4]))
print(torch.rand([3,4]))

tensor([[-1.5753e-25,  1.3985e-42,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0.2272, 0.2860, 0.5554, 0.2697],
        [0.4107, 0.8601, 0.3235, 0.4400],
        [0.6079, 0.2563, 0.8856, 0.5488]])


# 3 张量的方法和属性

In [11]:
# 1.tensor.item(),当tensor中只有一个元素可以用的时候
a =torch.tensor(np.arange(1))
print(a)
print(a.item()) #只有一个元素的时候可以用,返回一个python的标量,不可以用于多个元素的tensor
print('-'*50)

print(torch.Tensor([[[1]]]).item()) #获取一个tensor中的元素值
print('-'*50)


tensor([0], dtype=torch.int32)
0
--------------------------------------------------
1.0
--------------------------------------------------


In [12]:
# 2.Tensor转为ndarray
t2 = torch.Tensor([[3,4]])
print(t2)
print(t2.shape)
print(t2.numpy()) #tensor转为ndarray
print('-'*50)
print(t2.shape) #获取形状
print(t2.size()) #获取形状
print(t2.size(1))  #获取某个维度的形状,维度后的张量切片  第1维有两列
print(t2.size(0))   # 第0维有1行

tensor([[3., 4.]])
torch.Size([1, 2])
[[3. 4.]]
--------------------------------------------------
torch.Size([1, 2])
torch.Size([1, 2])
2
1


In [13]:
t2

tensor([[3., 4.]])

In [14]:
#写一个ndarray
array1 = np.array([[1,2,3],[4,5,6]])
print(id(array1))
array2=array1.reshape(3,2)
print(id(array2))

3055618326128
3055618324880


In [15]:
array2[0,0]=100
print(array1)
print(array2)

[[100   2   3]
 [  4   5   6]]
[[100   2]
 [  3   4]
 [  5   6]]


In [16]:
array1.ndim #获取维数

2

In [17]:
# 3.3.形状修改，tensor.view((3, 4)), 类似numpy中的reshape,是一种浅拷贝，仅仅形状发生改变,返回一个新的结果
print(t2)
t2 = torch.Tensor([[[3,4]]])
print(t2.size())
print(t2.view([1,2])) #[1,2]表示1行2列
print(t2.view([2])) # 一维tensor

tensor([[3., 4.]])
torch.Size([1, 1, 2])
tensor([[3., 4.]])
tensor([3., 4.])


In [18]:
b=t2.view([2, -1]) # -1表示自动计算
print(b)
print('-'*50)
print(t2) #t2的形状并没有发生改变
# https://pytorch.org/docs/stable/tensor_view.html
t2.untyped_storage().untyped().data_ptr() == b.untyped_storage().untyped().data_ptr() #判断两个tensor是否共享内存

tensor([[3.],
        [4.]])
--------------------------------------------------
tensor([[[3., 4.]]])


True

In [19]:
b[0,0]=100
print(b)
print(t2) #t2的形状并没有发生改变

tensor([[100.],
        [  4.]])
tensor([[[100.,   4.]]])


In [30]:
#3. 获取维数
print(t2.dim())
print(t2.size())

#4.获取最大值
print(t2.max())

#5.转置
t3 = torch.tensor([[1,3,4], [2,4,6]])
print(t3)
print(t3.t()) #转置



3
torch.Size([1, 1, 2])
tensor(100.)
tensor([[1, 3, 4],
        [2, 4, 6]])
tensor([[1, 2],
        [3, 4],
        [4, 6]])


In [21]:
# 交换轴,这里的permute和rollaxis功能类型
t4 = torch.tensor(np.arange(24).reshape(2,3,4))
print(t4.shape)
print("-"*50)
print(t4.transpose(0,1).shape)#交换0轴和1轴
print("-"*50)
print(t4.permute(1, 0, 2).shape)#交换0轴和1轴,功能同上
print("-"*50)
print(t4.permute(1, 2, 0).shape)#变为了3*4*2
print("-"*50)
print(t4.permute(2, 1, 0).shape)#变为了4*3*2

torch.Size([2, 3, 4])
--------------------------------------------------
torch.Size([3, 2, 4])
--------------------------------------------------
torch.Size([3, 2, 4])
--------------------------------------------------
torch.Size([3, 4, 2])
--------------------------------------------------
torch.Size([4, 3, 2])


In [22]:
t4.dtype

torch.int32

In [23]:
# 在方法后加_，会原地修改
x = torch.tensor(np.arange(12).reshape(3,4),dtype = torch.int8)
print(x)
y= torch.ones([3,4], dtype = torch.int64)
print(y)

print('-'*50)
x.sub_(y) # add_就地修改，不加下划线的会创建一个新的tensor来存储
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=torch.int8)
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
--------------------------------------------------
tensor([[-1,  0,  1,  2],
        [ 3,  4,  5,  6],
        [ 7,  8,  9, 10]], dtype=torch.int8)


In [24]:
#tensor取值,和np完全相同
t5 = torch.tensor(np.arange(12).reshape(3,4))
print(t5)
print(t5[1,2]) #取值
print(t5[1]) #取一行
print(t5[:,1]) #取一列
print(t5[1:3,1:3]) #取一部分
print(t5[1:3,:]) #取一部分



tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=torch.int32)
tensor(6, dtype=torch.int32)
tensor([4, 5, 6, 7], dtype=torch.int32)
tensor([1, 5, 9], dtype=torch.int32)
tensor([[ 5,  6],
        [ 9, 10]], dtype=torch.int32)
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=torch.int32)


In [25]:
#两个16行，1列的张量相减，求均值
t6 = torch.tensor(np.arange(16).reshape(16,1),dtype=torch.float32)
t7 = torch.tensor(np.arange(16,32).reshape(16,1),dtype=torch.float32)
print(t6)
print(t7)
((t6-t7)**2).mean()

tensor([[ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.],
        [13.],
        [14.],
        [15.]])
tensor([[16.],
        [17.],
        [18.],
        [19.],
        [20.],
        [21.],
        [22.],
        [23.],
        [24.],
        [25.],
        [26.],
        [27.],
        [28.],
        [29.],
        [30.],
        [31.]])


tensor(256.)

In [26]:
#初始化两个张量，一个3,4，一个3,1,运算与ndarray相同
t8 = torch.tensor(np.arange(12).reshape(3,4),dtype=torch.float32)
t9 = torch.tensor(np.arange(3).reshape(3,1),dtype=torch.float32)
print(t8)
print(t9)
t8-t9

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[0.],
        [1.],
        [2.]])


tensor([[0., 1., 2., 3.],
        [3., 4., 5., 6.],
        [6., 7., 8., 9.]])

In [27]:
"""
GPU中tensor的使用：
1.实例化device， torch.device("cpu" or "cuda:0"),选cuda:0需要torch.cuda.is_available()==true
2.tensor.to(device),把tensor转化为CUDA支持的tensor或者CPU支持的tensor
"""
print(torch.cuda.is_available())
if torch.cuda.is_available():
    device = torch.device("cuda") #cuda device对象
    y = torch.ones_like(x, device = device) #创建一个在cuda熵的tensor
    x = x.to(device) #把x转为cuda上的tensor
    z = x+y
    print(z)
    print(z.to("cpu", torch.double))

# torch.tensor([1.9806], device = "cuda:0")
device = torch.device("cpu")
x.to(device)

True
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], device='cuda:0', dtype=torch.int8)
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)


tensor([[-1,  0,  1,  2],
        [ 3,  4,  5,  6],
        [ 7,  8,  9, 10]], dtype=torch.int8)

In [28]:
# 张量的运算
t8 = torch.tensor(np.arange(12).reshape(3,4),dtype=torch.float32)
t9 = torch.tensor(np.arange(12).reshape(3,4),dtype=torch.float32)
t8*t9

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.]])

In [29]:
torch.mm(t8, t9.transpose(0,1)) #矩阵乘法

tensor([[ 14.,  38.,  62.],
        [ 38., 126., 214.],
        [ 62., 214., 366.]])