# numpy inf和nan

In [1]:
import numpy as np

# 创建一个nan和inf
a = np.nan
b = np.inf
print(a, type(a))  # nan <class 'float'>
print(b, type(b))  # inf <class 'float'>

nan <class 'float'>
inf <class 'float'>


In [2]:
# np.nan != np.nan
# 所以我们可以使用这两个结合使用判断nan的个数
print(np.nan == np.nan)
print(True == 1)
print(False == 0)
np.nan + 1  # nan和其他数运算的结果都是nan

False
True
True


nan

In [3]:
# --判断数组中为nan的个数
t = np.arange(24, dtype=float).reshape(4, 6)

# 将三行四列的数改成nan
t[3, 4] = np.nan
t[2, 4] = np.nan
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. nan 17.]
 [18. 19. 20. 21. nan 23.]]


In [4]:
# 可以使用np.count_nonzero() 来判断非零的个数
print(np.count_nonzero(t))

print(t != t)
print('-' * 50)
print(np.count_nonzero(t != t))  # 统计nan的个数

23
[[False False False False False False]
 [False False False False False False]
 [False False False False  True False]
 [False False False False  True False]]
--------------------------------------------------
2


In [5]:
# 将nan替换为0
t[np.isnan(t)] = 0
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15.  0. 17.]
 [18. 19. 20. 21.  0. 23.]]


In [6]:
# ------------练习： 处理数组中nan
t = np.arange(24).reshape(4, 6).astype('float')
# 将数组中的一部分替换nan
t[1, 3:] = np.nan
print(t)
print('-------------------')
print(t.shape)
print(id(t))

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
-------------------
(4, 6)
2493703459664


In [7]:
t.shape[1]  # 获取t数组的列数

6

In [8]:
# 遍历每一列，然后判断每一列是否有nan
for i in range(t.shape[1]):
    #获取当前列数据
    temp_col = t[:, i]

    # 判断当前列的数据中是否含有nan
    nan_num = np.count_nonzero(temp_col != temp_col)
    # 条件成立说明含有nan
    if nan_num != 0:
        # 将这一列不为nan的数据拿出来,并计算平均值
        temp_col_not_nan = temp_col[temp_col == temp_col]
        print(temp_col_not_nan)
        # 将nan替换成这一列的平均值
        temp_col[np.isnan(temp_col)] = np.mean(temp_col_not_nan)
print('-' * 50)
print(t)
print(id(t))

[ 3. 15. 21.]
[ 4. 16. 22.]
[ 5. 17. 23.]
--------------------------------------------------
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
2493703459664


In [9]:
print(np.inf == np.inf)
np.inf

True


inf

In [10]:
np.inf > -np.inf

True

In [12]:
# np.nan和任何数据运算的结果都是nan
t = np.arange(24).reshape(4, 6).astype('float')
# 将数组中的一部分替换nan
t[1, 3:] = np.nan
print(t)
print('-' * 50)
t1 = np.arange(24).reshape(4, 6).astype('float')
t + t1

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
--------------------------------------------------


array([[ 0.,  2.,  4.,  6.,  8., 10.],
       [12., 14., 16., nan, nan, nan],
       [24., 26., 28., 30., 32., 34.],
       [36., 38., 40., 42., 44., 46.]])

In [13]:
arr = np.array([-1, 0])
print(arr)  # [-1  0]
print(arr[0] / arr[1])  #1除0就会得到inf

[-1  0]
-inf


C:\Users\q1209\AppData\Local\Temp\ipykernel_5072\773640058.py:3: RuntimeWarning: divide by zero encountered in scalar divide
  print(arr[0] / arr[1])  #1除0就会得到inf


In [14]:
np.nan + np.inf

nan

# 转置和轴滚动

In [16]:
#对换数组的维度
import numpy as np

a = np.arange(12).reshape(3, 4)
print('原数组：')
print(a)
print('\n')

print('对换数组：')
print(np.transpose(a))

# 与transpose一致
print('转置数组：')
print(a.T)

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
转置数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [17]:
# 函数用于交换数组的两个轴
t1 = np.arange(24).reshape(4, 6)
re1 = t1.swapaxes(1, 0)

print(' 原 数 组 ：')
print(t1)
print('\n')

print(re1.shape)
print('调用 swapaxes 函数后的数组：')
print(re1)


 原 数 组 ：
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


(6, 4)
调用 swapaxes 函数后的数组：
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [19]:
#如果是3维及以上，称为轴交换
t3 = np.arange(60).reshape(3, 4, 5)
print(t3.shape)
print('-' * 50)

t3 = np.swapaxes(t3, 1, 2)
print(t3.shape)
# print(t3) # 数据不用记住，不用观察

(3, 4, 5)
--------------------------------------------------
(3, 5, 4)
[[[ 0  5 10 15]
  [ 1  6 11 16]
  [ 2  7 12 17]
  [ 3  8 13 18]
  [ 4  9 14 19]]

 [[20 25 30 35]
  [21 26 31 36]
  [22 27 32 37]
  [23 28 33 38]
  [24 29 34 39]]

 [[40 45 50 55]
  [41 46 51 56]
  [42 47 52 57]
  [43 48 53 58]
  [44 49 54 59]]]


In [21]:
# 数组的轴滚动,swapaxes每次只能交换两个轴，没有rollaxis方便，默认情况下轴滚动最前面
a = np.ones((3, 4, 5, 6))
c=np.rollaxis(a, 2).shape   # (5, 3, 4, 6)
print(c)

b = np.rollaxis(a, 3, 1)    # (3, 6, 4, 5)
print(b.shape)

(5, 3, 4, 6)
(3, 6, 4, 5)


In [22]:
c = np.rollaxis(b, 1, 4)  #轴会滚动，直到它位于此位置之前
print(c.shape)  # (3, 4, 5, 6)

(3, 4, 5, 6)


In [23]:
#数据拷贝，copy()和赋值的区别
b = np.array([[1, 2, 3], [1, 2, 3]])
print(b.shape)
a = b.copy()
a

(2, 3)


array([[1, 2, 3],
       [1, 2, 3]])

In [24]:
b[0, 0] = 3
print(b)
a

[[3 2 3]
 [1 2 3]]


array([[1, 2, 3],
       [1, 2, 3]])

In [25]:
# 均匀分布的随机数生成
arr = np.random.rand(2, 3, 4)
print(arr)

[[[0.62897065 0.82014857 0.09319964 0.30030936]
  [0.68335656 0.63873765 0.24247325 0.36837423]
  [0.5071341  0.58143359 0.01690968 0.22865427]]

 [[0.47435009 0.44865203 0.03579729 0.88456436]
  [0.1834595  0.13669744 0.99372364 0.42380254]
  [0.02854312 0.10577943 0.708173   0.90532591]]]


In [26]:
names = 'zhangsan,lisi,wangwu,zhaoliu,sunqi'
#写入文件
with open('names.csv', 'w') as f:
    f.write(names)
    f.write('\n')
    f.write('12,23,34,45,56')